
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using ShootingRange.BusinessObjectContracts;
using ShootingRange.Entities;

namespace ShootingRange.BusinessObjects
{
  
  public static class EntityObjectMapper
  {
    // mapper for "BestShot" entity object
    public static t_bestshot MapToEntity(IBestShot record)
    {
      var entity = new t_bestshot();
      entity.BestShotId = record.BestShotId;
      entity.ShotId = record.ShotId;
      return entity;
    }
    
    // mapper for "Club" entity object
    public static t_club MapToEntity(IClub record)
    {
      var entity = new t_club();
      entity.ClubId = record.ClubId;
      entity.ClubName = record.ClubName;
      entity.Zip = record.Zip;
      entity.City = record.City;
      return entity;
    }
    
    // mapper for "Event" entity object
    public static t_event MapToEntity(IEvent record)
    {
      var entity = new t_event();
      entity.EventId = record.EventId;
      entity.EventName = record.EventName;
      entity.StartDate = record.StartDate;
      entity.EndDate = record.EndDate;
      return entity;
    }
    
    // mapper for "Group" entity object
    public static t_group MapToEntity(IGroup record)
    {
      var entity = new t_group();
      entity.GroupId = record.GroupId;
      entity.GroupName = record.GroupName;
      return entity;
    }
    
    // mapper for "Order" entity object
    public static t_order MapToEntity(IOrder record)
    {
      var entity = new t_order();
      entity.OrderId = record.OrderId;
      entity.ShooterId = record.ShooterId;
      entity.OrderItemId = record.OrderItemId;
      return entity;
    }
    
    // mapper for "OrderItem" entity object
    public static t_orderitem MapToEntity(IOrderItem record)
    {
      var entity = new t_orderitem();
      entity.OrderItemId = record.OrderItemId;
      entity.ProgramItemId = record.ProgramItemId;
      entity.ItemName = record.ItemName;
      entity.Price = record.Price;
      return entity;
    }
    
    // mapper for "Person" entity object
    public static t_person MapToEntity(IPerson record)
    {
      var entity = new t_person();
      entity.PersonId = record.PersonId;
      entity.LastName = record.LastName;
      entity.FirstName = record.FirstName;
      entity.Street = record.Street;
      entity.Zip = record.Zip;
      entity.City = record.City;
      entity.Phone = record.Phone;
      entity.Email = record.Email;
      entity.BirthDate = record.BirthDate;
      entity.LicenseNumber = record.LicenseNumber;
      return entity;
    }
    
    // mapper for "ProgramItem" entity object
    public static t_programitem MapToEntity(IProgramItem record)
    {
      var entity = new t_programitem();
      entity.ProgramItemId = record.ProgramItemId;
      entity.ItemName = record.ItemName;
      entity.ProgramNumber = record.ProgramNumber;
      return entity;
    }
    
    // mapper for "ProgramSubtotal" entity object
    public static t_programsubtotal MapToEntity(IProgramSubtotal record)
    {
      var entity = new t_programsubtotal();
      entity.ProgramSubtotalId = record.ProgramSubtotalId;
      entity.ProgramItemId = record.ProgramItemId;
      entity.SubtotalNumber = record.SubtotalNumber;
      entity.NumberOfShots = record.NumberOfShots;
      return entity;
    }
    
    // mapper for "Session" entity object
    public static t_session MapToEntity(ISession record)
    {
      var entity = new t_session();
      entity.SessionId = record.SessionId;
      entity.ProgramItemId = record.ProgramItemId;
      entity.ShooterId = record.ShooterId;
      entity.LaneNumber = record.LaneNumber;
      return entity;
    }
    
    // mapper for "SessionSubtotal" entity object
    public static t_sessionsubtotal MapToEntity(ISessionSubtotal record)
    {
      var entity = new t_sessionsubtotal();
      entity.SessionSubtotalId = record.SessionSubtotalId;
      entity.SessionId = record.SessionId;
      entity.BestShotId = record.BestShotId;
      entity.SubtotalNumber = record.SubtotalNumber;
      return entity;
    }
    
    // mapper for "Shooter" entity object
    public static t_shooter MapToEntity(IShooter record)
    {
      var entity = new t_shooter();
      entity.ShooterId = record.ShooterId;
      entity.PersonId = record.PersonId;
      entity.EventId = record.EventId;
      entity.ClubId = record.ClubId;
      entity.GroupId = record.GroupId;
      entity.ShooterNumber = record.ShooterNumber;
      return entity;
    }
    
    // mapper for "Shot" entity object
    public static t_shot MapToEntity(IShot record)
    {
      var entity = new t_shot();
      entity.ShotId = record.ShotId;
      entity.SubtotalId = record.SubtotalId;
      entity.PrimaryScore = record.PrimaryScore;
      entity.SecondaryScore = record.SecondaryScore;
      entity.ValueX = record.ValueX;
      entity.ValueY = record.ValueY;
      return entity;
    }
    
  }
  
  }
