//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShootingRange.BusinessObjectContracts
{
  using Repository;
  using System;
  using System.Collections.Generic;
  
  public interface IPerson
  {
      int PersonId { get; set; }
      string LastName { get; set; }
      string FirstName { get; set; }
      string Street { get; set; }
      Nullable<int> Zip { get; set; }
      string City { get; set; }
      string Phone { get; set; }
      string Email { get; set; }
      Nullable<System.DateTime> BirthDate { get; set; }
      Nullable<int> LicenseNumber { get; set; }
  }
}

