//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShootingRange.BusinessObjectContracts
{
  using Repository;
  using System;
  using System.Collections.Generic;
  
  public interface IProgramSubtotal
  {
      int ProgramSubtotalId { get; set; }
      int ProgramItemId { get; set; }
      Nullable<int> SubtotalNumber { get; set; }
      Nullable<int> NumberOfShots { get; set; }
  }
}

