//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShootingRange.BusinessObjectContracts
{
  using Repository;
  using System;
  using System.Collections.Generic;
  
  public interface ISessionSubtotal
  {
      int SessionSubtotalId { get; set; }
      int SessionId { get; set; }
      Nullable<int> BestShotId { get; set; }
      int SubtotalNumber { get; set; }
  }
}

