//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShootingRange.BusinessObjectContracts
{
  using Repository;
  using System;
  using System.Collections.Generic;
  
  public interface IShot
  {
      int ShotId { get; set; }
      int SubtotalId { get; set; }
      decimal PrimaryScore { get; set; }
      Nullable<decimal> SecondaryScore { get; set; }
      Nullable<decimal> ValueX { get; set; }
      Nullable<decimal> ValueY { get; set; }
  }
}

