//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShootingRange.BusinessObjectContracts
{
  using Repository;
  using System;
  using System.Collections.Generic;
  
  public interface IShooter
  {
      int ShooterId { get; set; }
      int PersonId { get; set; }
      int EventId { get; set; }
      Nullable<int> ClubId { get; set; }
      Nullable<int> GroupId { get; set; }
      int ShooterNumber { get; set; }
  }
}

