//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_orderitem
    {
        public t_orderitem()
        {
            this.t_order = new HashSet<t_order>();
        }
    
        public int OrderItemId { get; set; }
        public Nullable<int> ProgramItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<t_order> t_order { get; set; }
        public virtual t_programitem t_programitem { get; set; }
    }
}
