//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_person
    {
        public t_person()
        {
            this.t_shooter = new HashSet<t_shooter>();
        }
    
        public int PersonId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Street { get; set; }
        public Nullable<int> Zip { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> LicenseNumber { get; set; }
    
        public virtual ICollection<t_shooter> t_shooter { get; set; }
    }
}
