//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShootingRange.Entities
{
  using System;
  using System.Collections.Generic;
  
  public partial class t_shot
  {
      public t_shot()
      {
          this.t_bestshot = new HashSet<t_bestshot>();
      }
  
  
      public int ShotId { get; set; }
  
      public int SubtotalId { get; set; }
  
      public decimal PrimaryScore { get; set; }
  
      public Nullable<decimal> SecondaryScore { get; set; }
  
      public Nullable<decimal> ValueX { get; set; }
  
      public Nullable<decimal> ValueY { get; set; }
  
      public virtual ICollection<t_bestshot> t_bestshot { get; set; }
      public virtual t_sessionsubtotal t_sessionsubtotal { get; set; }
  }
}

