//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_club
    {
        public t_club()
        {
            this.t_shooter = new HashSet<t_shooter>();
        }
    
        public int ClubId { get; set; }
        public string ClubName { get; set; }
        public Nullable<int> Zip { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<t_shooter> t_shooter { get; set; }
    }
}
