//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_collectionshooter
    {
        public int CollectionShooterId { get; set; }
        public int ShooterId { get; set; }
        public int ShooterCollectionId { get; set; }
    
        public virtual t_shootercollection t_shootercollection { get; set; }
        public virtual t_shooter t_shooter { get; set; }
    }
}
