//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_collectionshooter
    {
        public int CollectionShooterId { get; set; }
        public int ShooterId { get; set; }
        public int ShooterCollectionId { get; set; }
    
        public virtual t_shootercollection t_shootercollection { get; set; }
        public virtual t_shooter t_shooter { get; set; }
    }
}
