//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_event
    {
        public t_event()
        {
            this.t_shooter = new HashSet<t_shooter>();
        }
    
        public int EventId { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int ShooterNumberConfigId { get; set; }
    
        public virtual ICollection<t_shooter> t_shooter { get; set; }
        public virtual t_shooternumberconfig t_shooternumberconfig { get; set; }
    }
}
