//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_groupdescription
    {
        public t_groupdescription()
        {
            this.t_group = new HashSet<t_group>();
        }
    
        public int GroupDescriptionId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<t_group> t_group { get; set; }
    }
}
