//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_orderitem
    {
        public t_orderitem()
        {
            this.t_order = new HashSet<t_order>();
        }
    
        public int OrderItemId { get; set; }
        public Nullable<int> ProgramItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<t_order> t_order { get; set; }
        public virtual t_programitem t_programitem { get; set; }
    }
}
