//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_participation
    {
        public t_participation()
        {
            this.t_shootercollectionparticipation = new HashSet<t_shootercollectionparticipation>();
            this.t_shooterparticipation = new HashSet<t_shooterparticipation>();
        }
    
        public int ParticipationId { get; set; }
        public string Description { get; set; }
        public bool AllowCollectionParticipation { get; set; }
        public bool AllowSingleParticipation { get; set; }
    
        public virtual ICollection<t_shootercollectionparticipation> t_shootercollectionparticipation { get; set; }
        public virtual ICollection<t_shooterparticipation> t_shooterparticipation { get; set; }
    }
}
