//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_participationdescription
    {
        public t_participationdescription()
        {
            this.t_participation = new HashSet<t_participation>();
        }
    
        public int ParticipationDescriptionId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<t_participation> t_participation { get; set; }
    }
}
