//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_participation
    {
        public t_participation()
        {
            this.t_shooterparticipation = new HashSet<t_shooterparticipation>();
        }
    
        public int ParticipationId { get; set; }
        public string ParticipationName { get; set; }
        public int ParticipationDescriptionId { get; set; }
    
        public virtual t_participationdescription t_participationdescription { get; set; }
        public virtual ICollection<t_shooterparticipation> t_shooterparticipation { get; set; }
    }
}
