//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_participation
    {
        public t_participation()
        {
            this.t_shootercollectionparticipation = new HashSet<t_shootercollectionparticipation>();
            this.t_shooterparticipation = new HashSet<t_shooterparticipation>();
        }
    
        public int ParticipationId { get; set; }
        public string Description { get; set; }
        public bool AllowCollectionParticipation { get; set; }
        public bool AllowSingleParticipation { get; set; }
    
        public virtual ICollection<t_shootercollectionparticipation> t_shootercollectionparticipation { get; set; }
        public virtual ICollection<t_shooterparticipation> t_shooterparticipation { get; set; }
    }
}
