//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_programitem
    {
        public t_programitem()
        {
            this.t_orderitem = new HashSet<t_orderitem>();
            this.t_programsubtotal = new HashSet<t_programsubtotal>();
            this.t_session = new HashSet<t_session>();
        }
    
        public int ProgramItemId { get; set; }
        public string ItemName { get; set; }
        public int ProgramNumber { get; set; }
    
        public virtual ICollection<t_orderitem> t_orderitem { get; set; }
        public virtual ICollection<t_programsubtotal> t_programsubtotal { get; set; }
        public virtual ICollection<t_session> t_session { get; set; }
    }
}
