//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_programsubtotal
    {
        public int ProgramSubtotalId { get; set; }
        public int ProgramItemId { get; set; }
        public Nullable<int> SubtotalOrdinal { get; set; }
        public Nullable<int> NumberOfShots { get; set; }
    
        public virtual t_programitem t_programitem { get; set; }
    }
}
