//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_sessionsubtotal
    {
        public t_sessionsubtotal()
        {
            this.t_shot = new HashSet<t_shot>();
        }
    
        public int SessionSubtotalId { get; set; }
        public int SessionId { get; set; }
        public Nullable<int> BestShotId { get; set; }
        public int SubtotalOrdinal { get; set; }
    
        public virtual t_bestshot t_bestshot { get; set; }
        public virtual t_session t_session { get; set; }
        public virtual ICollection<t_shot> t_shot { get; set; }
    }
}
