//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shot
    {
        public t_shot()
        {
            this.t_bestshot = new HashSet<t_bestshot>();
            this.t_sessionsubtotal1 = new HashSet<t_sessionsubtotal>();
        }
    
        public int ShotId { get; set; }
        public int SubtotalId { get; set; }
        public int ShotOrdinal { get; set; }
        public decimal PrimaryScore { get; set; }
        public Nullable<decimal> SecondaryScore { get; set; }
        public Nullable<decimal> ValueX { get; set; }
        public Nullable<decimal> ValueY { get; set; }
    
        public virtual ICollection<t_bestshot> t_bestshot { get; set; }
        public virtual t_sessionsubtotal t_sessionsubtotal { get; set; }
        public virtual ICollection<t_sessionsubtotal> t_sessionsubtotal1 { get; set; }
    }
}
