//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shooter
    {
        public t_shooter()
        {
            this.t_order = new HashSet<t_order>();
            this.t_session = new HashSet<t_session>();
            this.t_shooterparticipation = new HashSet<t_shooterparticipation>();
        }
    
        public int ShooterId { get; set; }
        public int PersonId { get; set; }
        public int EventId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public int ShooterNumber { get; set; }
    
        public virtual t_club t_club { get; set; }
        public virtual ICollection<t_order> t_order { get; set; }
        public virtual t_person t_person { get; set; }
        public virtual ICollection<t_session> t_session { get; set; }
        public virtual ICollection<t_shooterparticipation> t_shooterparticipation { get; set; }
    }
}
