//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shootercollection
    {
        public t_shootercollection()
        {
            this.t_collectionshooter = new HashSet<t_collectionshooter>();
            this.t_shootercollectionparticipation = new HashSet<t_shootercollectionparticipation>();
        }
    
        public int ShooterCollectionId { get; set; }
        public string CollectionName { get; set; }
    
        public virtual ICollection<t_collectionshooter> t_collectionshooter { get; set; }
        public virtual ICollection<t_shootercollectionparticipation> t_shootercollectionparticipation { get; set; }
    }
}
