//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shootercollection
    {
        public t_shootercollection()
        {
            this.t_collectionshooter = new HashSet<t_collectionshooter>();
            this.t_shootercollectionparticipation = new HashSet<t_shootercollectionparticipation>();
        }
    
        public int ShooterCollectionId { get; set; }
        public string CollectionName { get; set; }
    
        public virtual ICollection<t_collectionshooter> t_collectionshooter { get; set; }
        public virtual ICollection<t_shootercollectionparticipation> t_shootercollectionparticipation { get; set; }
    }
}
