//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shooternumberconfig
    {
        public t_shooternumberconfig()
        {
            this.t_event = new HashSet<t_event>();
        }
    
        public int ShooterNumberConfigId { get; set; }
        public int LastGivenShooterNumber { get; set; }
        public int ShooterNumberIncrement { get; set; }
    
        public virtual ICollection<t_event> t_event { get; set; }
    }
}
