//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shooterparticipation
    {
        public int ShooterParticipationId { get; set; }
        public int ShooterId { get; set; }
        public int ParticipationId { get; set; }
    
        public virtual t_participation t_participation { get; set; }
        public virtual t_shooter t_shooter { get; set; }
    }
}
