//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShootingRange.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_shooter
    {
        public t_shooter()
        {
            this.t_collectionshooter = new HashSet<t_collectionshooter>();
            this.t_order = new HashSet<t_order>();
            this.t_session = new HashSet<t_session>();
            this.t_shooterparticipation = new HashSet<t_shooterparticipation>();
        }
    
        public int ShooterId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public int ShooterNumber { get; set; }
    
        public virtual t_club t_club { get; set; }
        public virtual ICollection<t_collectionshooter> t_collectionshooter { get; set; }
        public virtual ICollection<t_order> t_order { get; set; }
        public virtual t_person t_person { get; set; }
        public virtual ICollection<t_session> t_session { get; set; }
        public virtual ICollection<t_shooterparticipation> t_shooterparticipation { get; set; }
    }
}
